// reactjs/src/components/TodoApp.tsx
import React, { useState } from 'react'
import {
  Card,
  CardContent,
  TextField,
  Button,
  Box,
  Typography,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  IconButton,
  Checkbox,
  Paper,
} from '@mui/material'
import DeleteIcon from '@mui/icons-material/Delete'
import './TodoApp.css'

interface Todo {
  id: number
  text: string
  completed: boolean
}

const TodoApp: React.FC = () => {
  const [todos, setTodos] = useState<Todo[]>([])
  const [inputValue, setInputValue] = useState<string>('')
  const [nextId, setNextId] = useState<number>(1)

  const addTodo = (): void => {
    if (inputValue.trim()) {
      setTodos([
        ...todos,
        {
          id: nextId,
          text: inputValue,
          completed: false,
        },
      ])
      setNextId(nextId + 1)
      setInputValue('')
    }
  }

  const toggleTodo = (id: number): void => {
    setTodos(
      todos.map((todo) =>
        todo.id === id ? { ...todo, completed: !todo.completed } : todo
      )
    )
  }

  const deleteTodo = (id: number): void => {
    setTodos(todos.filter((todo) => todo.id !== id))
  }

  const clearCompleted = (): void => {
    setTodos(todos.filter((todo) => !todo.completed))
  }

  const handleKeyPress = (e: React.KeyboardEvent<HTMLDivElement>): void => {
    if (e.key === 'Enter') {
      addTodo()
    }
  }

  const completedCount = todos.filter((t) => t.completed).length
  const totalCount = todos.length

  return (
    <Box className="todo-container">
      <Card className="todo-card">
        <Box className="card-header">
          <Typography variant="h3" className="header-title">
            My Todos
          </Typography>
          <Typography variant="body2" className="subtitle">
            {completedCount} of {totalCount} completed
          </Typography>
        </Box>

        <CardContent className="card-content">
          <Box className="input-section">
            <TextField
              fullWidth
              placeholder="Add a new todo"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyPress={handleKeyPress}
              variant="outlined"
              size="small"
              className="todo-input"
            />
            <Button
              variant="contained"
              onClick={addTodo}
              className="btn-add"
            >
              Add
            </Button>
          </Box>

          {todos.length === 0 ? (
            <Box className="empty-state">
              <Typography variant="body1">
                No todos yet. Add one to get started!
              </Typography>
            </Box>
          ) : (
            <Paper className="todo-list">
              <List>
                {todos.map((todo) => (
                  <ListItem
                    key={todo.id}
                    className={`todo-item ${todo.completed ? 'completed' : ''}`}
                  >
                    <ListItemIcon>
                      <Checkbox
                        checked={todo.completed}
                        onChange={() => toggleTodo(todo.id)}
                        sx={{ color: '#667eea' }}
                      />
                    </ListItemIcon>
                    <ListItemText
                      primary={todo.text}
                      className="todo-text"
                    />
                    <IconButton
                      edge="end"
                      aria-label="delete"
                      onClick={() => deleteTodo(todo.id)}
                      className="btn-delete"
                    >
                      <DeleteIcon />
                    </IconButton>
                  </ListItem>
                ))}
              </List>
            </Paper>
          )}

          {todos.length > 0 && (
            <Box className="actions">
              <Button
                variant="contained"
                onClick={clearCompleted}
                className="btn-clear"
              >
                Clear Completed
              </Button>
            </Box>
          )}
        </CardContent>
      </Card>
    </Box>
  )
}

export default TodoApp

// SolidJS/src/components/TodoApp.tsx
import { createSignal, For } from 'solid-js'

interface Todo {
  id: number
  text: string
  completed: boolean
}

export default function TodoApp() {
  const [todos, setTodos] = createSignal<Todo[]>([])
  const [inputValue, setInputValue] = createSignal<string>('')
  const [nextId, setNextId] = createSignal<number>(1)

  const addTodo = () => {
    const value = inputValue().trim()
    if (value) {
      setTodos([
        ...todos(),
        {
          id: nextId(),
          text: value,
          completed: false,
        },
      ])
      setNextId(nextId() + 1)
      setInputValue('')
    }
  }

  const toggleTodo = (id: number) => {
    setTodos(
      todos().map((todo) =>
        todo.id === id ? { ...todo, completed: !todo.completed } : todo
      )
    )
  }

  const deleteTodo = (id: number) => {
    setTodos(todos().filter((todo) => todo.id !== id))
  }

  const clearCompleted = () => {
    setTodos(todos().filter((todo) => !todo.completed))
  }

  const handleKeyPress = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      addTodo()
    }
  }

  const completedCount = () => todos().filter((t) => t.completed).length
  const totalCount = () => todos().length

  return (
    <div class="todo-container">
      <div class="todo-card">
        <div class="card-header">
          <h1>My Todos</h1>
          <p class="subtitle">
            {completedCount()} of {totalCount()} completed
          </p>
        </div>

        <div class="card-content">
          <div class="input-section">
            <input
              type="text"
              class="todo-input"
              placeholder="Add a new todo"
              value={inputValue()}
              onInput={(e) => setInputValue(e.currentTarget.value)}
              onKeyPress={handleKeyPress}
            />
            <button class="btn btn-primary" onClick={addTodo}>
              Add
            </button>
          </div>

          {todos().length === 0 ? (
            <div class="empty-state">
              <p>No todos yet. Add one to get started!</p>
            </div>
          ) : (
            <div class="todo-list">
              <For each={todos()}>
                {(todo) => (
                  <div
                    class={`todo-item ${todo.completed ? 'completed' : ''}`}
                  >
                    <input
                      type="checkbox"
                      class="todo-checkbox"
                      checked={todo.completed}
                      onChange={() => toggleTodo(todo.id)}
                    />
                    <span class="todo-text">{todo.text}</span>
                    <button
                      class="btn-delete"
                      onClick={() => deleteTodo(todo.id)}
                      title="Delete"
                    >
                      delete
                    </button>
                  </div>
                )}
              </For>
            </div>
          )}

          {todos().length > 0 && (
            <div class="actions">
              <button class="btn btn-secondary" onClick={clearCompleted}>
                Clear Completed
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
